---
development:
  cloud_name: solectwolubiana
  api_key: '271969941577164'
  api_secret: XviRqeW2WmgXxbDTWDcGd1KKeSc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: solectwolubiana
  api_key: '271969941577164'
  api_secret: XviRqeW2WmgXxbDTWDcGd1KKeSc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: solectwolubiana
  api_key: '271969941577164'
  api_secret: XviRqeW2WmgXxbDTWDcGd1KKeSc
  enhance_image_tag: true
  static_image_support: false
